opt_out_usage

desc 'Create a pre-release version by pushing a tag to GitHub, and publishing plugins to Pub.dev'
lane :unstable do
  next_version = calculate_next_canary_version
  UI.message("Releasing unstable version: #{next_version}")

  # Increment all pubspecs
  increment_versions(version: next_version)

  # Create tag and push to origin
  add_tag(version: next_version)

  # Publish to Pub.dev
  release_plugins
end

desc 'Create a release version by building and committing a changelog, pushing a tag to GitHub, and publishing plugins to Pub.dev'
lane :stable do
  next_version, commits = calculate_next_release_version
  UI.message("Releasing version: #{next_version}")

  # Increment all specs and plists
  increment_versions(version: next_version)

  changelog = build_changelog(version: next_version, commits: commits)

  # Commit and push
  release_commit(version: next_version)

  # Create tag and push to origin
  add_tag(version: next_version)

  # Publish plugins
  release_plugins

  post_release(version: next_version, changelog: changelog)
end

desc 'Increment versions'
private_lane :increment_versions do |options|
  version = options[:version].to_s

  # AmplifyPods.pods.each do |pod|
  #   spec, constants, plist_paths = pod.values

  #   UI.message("Incrementing version for #{spec}")

  #   constants.each do |constant|
  #     set_key_value(file: spec, key: constant, value: version)
  #   end

  #   plist_paths.each do |plist_path|
  #     set_info_plist_value(path: plist_path, key: PLIST_KEY, value: version)
  #   end

  #   # One-offs
  #   set_key_value(file: "AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift", key: "version", value: version)
  #   set_key_value(file: "build-support/dependencies.rb", key: "AMPLIFY_VERSION", value: version)
  # end
end

desc 'Commit and push'
private_lane :release_commit do |options|
  next_version = options[:version]

  sh('git', 'config', '--global', 'user.email', ENV['GITHUB_EMAIL'])
  sh('git', 'config', '--global', 'user.name', ENV['GITHUB_USER'])

  commit_message = "chore: release #{next_version} [skip ci]"
  sh('git', 'commit', '-am', commit_message)

  # push to origin
  sh('git', 'push', 'origin', 'release')
end

desc 'Tag in git and push to GitHub'
private_lane :add_tag do |options|
  next_version = options[:version]
  next_tag = "v#{next_version}"

  add_git_tag(tag: next_tag)
  push_git_tags(tag: next_tag)
end

desc 'Release plugins'
private_lane :release_plugins do
end

desc 'Post-release'
private_lane :post_release do |options|
  version = options[:version].to_s
  changelog = options[:changelog]
  tag = "v#{version}"
  plugin_root = File.expand_path("#{ENV['CIRCLE_WORKING_DIRECTORY']}/AmplifyPlugins")
end

def with_retry(retries = 5, wait = 10)
  yield
rescue e
  retries -= 1
  raise e if retries.zero?
  UI.error("Error occurred: #{exception}; retrying...")
  sleep(wait)
  retry
end
